// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnybvcuvytzgjahtkomz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJueWJ2Y3V2eXR6Z2phaHRrb216Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MjU5NTEsImV4cCI6MjA3MjEwMTk1MX0.yYQSPuNSIhxZVzC4r4mKRk0v9bWwyXYGb5ak3NZPd30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});